facebook:
  client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
  resource:
      userInfoUri: https://graph.facebook.com/me


github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

    resource:
        filter-order: 3


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oneid?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8&serverTimezone=UTC
    username: oneid
    password: oneid
    validation-query:  SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    min-idle: 0
    max-active: 50
    max-wait: 30000
    test-on-borrow: true
    test-while-idle: true
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .html


  session:
    store-type: jdbc
    cookie:
      domain: .zibann.kr

# spring.session.jdbc.initializer.enabled= # Create the required session tables on startup if necessary. Enabled automatically if the default table name is set or a custom schema is configured.
# spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-@@platform@@.sql # Path to the SQL file to use to initialize the database schema.
# spring.session.jdbc.table-name=SPRING_SESSION # Name of database table used to store sessions.

server:
  port: 10021
